const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_quotes",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"internal_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"supplier_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"supplier","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"valid_day","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hash","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"igst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"service","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
