const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_receive_payments",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"from_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"received_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"paid_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"checked_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"checked_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"verified_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"verified_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"char","auto":false,"nullable":true,"hasDefault":true},
  ],
});
