const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_fuel_sales",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"time_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_cash","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_cash_open","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"json_total_cash","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"json_total_cash_open","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"json_total_cash_count","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"credit_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"json_credit_amount","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"kh_rate","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"json_bank_amount","type":"text","auto":false,"nullable":true,"hasDefault":false},
  ],
});
