const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_payments_requested",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"transaction_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"paid_by","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"cheque_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_cvv2","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_holder","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_month","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_year","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cc_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"amount","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"amount_usd","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"amount_khr","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"amount_thb","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"currency","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cheque_date","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cheque_number","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"account_number","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"account_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currencies","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approval_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"write_off","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"paid_amount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency_rate","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"purchase_deposit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"bank_charge","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"payment_term","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"penalty_paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"account_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
