const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_loan_reschedule",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"user_id","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_id","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_method","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"outstanding_balance","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"disburse_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"first_payment_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"disburse_amount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_interest","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_amount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principle_nego","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term_nego","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_nego","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"register_date","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"percent","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reschedule_time","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
  ],
});
