const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_deposits",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"company_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"amount","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"amount_usd","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"amount_khr","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"amount_thb","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"paid_by","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"account_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"po_reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"so_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"po_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"opening","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
