const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_att_approve_attedances",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"employee_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"start_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"end_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"month","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"year","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"working_day","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"present","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"permission","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"absent","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weekend_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"normal_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"leave_early","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weekend","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"annual_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"special_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sick_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"other_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"half_pay_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"food_fee","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pre_salary_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salary_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
