const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_account_settings",
  primaryKey: ["id","biller_id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"default_open_balance","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_sale","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"other_income","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_sale_discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_sale_tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_sale_freight","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_sale_deposit","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_receivable","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_purchase","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_purchase_discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_purchase_tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_purchase_freight","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_purchase_deposit","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_payable","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_stock","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_stock_adjust","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_cost","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_payroll","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_cash","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_credit_card","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_gift_card","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_cheque","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_loan","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_retained_earnings","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_cost_variant","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_interest_income","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_transfer_owner","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_tax_expense","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_vat_payable","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_salary_tax_payable","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_tax_duties_expense","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_salary_expense","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_salary_payable","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_product_tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_product_discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"accounting","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_expense","type":"tinyint","auto":false,"nullable":false,"hasDefault":false},
    {"name":"default_payment_pos","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_write_off","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pawn_stock_acc","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"installment_outstanding_acc","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_stock_using","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_expense","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_cost_adjustment","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"consignment_acc","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_stock_acc","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"credit_note","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"debit_note","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_convert_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
