const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_purchases_order",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"project_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"purchase_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"supplier_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"supplier","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"note","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"total","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rejected_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"surcharge","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"suspend_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no_tax","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"tax_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_type","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_type","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"request_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deadline","type":"date","auto":false,"nullable":false,"hasDefault":false},
    {"name":"eta","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"received","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
  ],
});
