const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_credit_note_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"credit_note_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_unit_price","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"unit_price","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_quantity","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"quantity","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"real_quantity","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_tax","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_discount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_price","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_comment_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"width","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"height","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"square","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"square_qty","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"foc_qty","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"comment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
