const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_loan_products",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principal_amount_default","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principal_amount_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principal_amount_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_default","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term_default","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term_min","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term_max","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"frequency","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_method","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_period","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grace_interest_charge","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_repayment_penalty_recurring","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_repayment_penalty_calculate","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_repayment_penalty_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_repayment_penalty_period","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"charge_ids","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_bank_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"loan_portfolio_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_receivable_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_income_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"penalty_income_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
