const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sales_order",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"project_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"staff_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"sale_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_status","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"delivery_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_items","type":"smallint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pos","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"paid","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"surcharge","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_sale_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_sale_total","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"rounding","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"suspend_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"api","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shop","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reserve_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hash","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"manual_payment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"module_type","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"weight","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"height","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"temperature","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency_rate_kh","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_method","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"image","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"store_sale","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"symptoms","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"symptoms_description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"patience_type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"diagnosis_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bed_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"location_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
