const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_gl_trans",
  primaryKey: ["tran_id"],
  hidden: [],
  columns: [
    {"name":"tran_id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"tran_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tran_no","type":"bigint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"tran_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sectionid","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"account_code","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"narrative","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"amount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"description","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gov_tax","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_gov_tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"people_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"invoice_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"ref_type","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"people","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status_tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"supplier_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payroll_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"expense_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"depreciation_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reconciled","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"activity_type","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
