const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sh_student_statuses",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"academic_year","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"s_academic_year","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"from_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"student_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"review_status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"review_note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"review_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"review_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"review_attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"study_info_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"link_scan","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
