const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_deliveries",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"clear_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_order_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"do_reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"sale_reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"so_reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"clear_reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"clear_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"clear_created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"paid_by","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivered_by","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"received_by","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"money_collection","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"collection_amount","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"clear_amount","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"balance","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"send_number","type":"int","auto":false,"nullable":false,"hasDefault":false},
  ],
});
