const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_audit_order_item",
  primaryKey: ["Id"],
  hidden: [],
  columns: [
    {"name":"Id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"audit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"suspended_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"qty","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"new_qty","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"last_order","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"order_status","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"type","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"user_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tran_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"status","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"stock_type","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"print_index","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"row_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"ordering_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_row_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"comment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"suspend_note","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"print_status","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
