const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_pay_pre_salary_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"att_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"basic_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"present","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"annual_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sick_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"special_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pre_salary_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gross_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_paid","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"employee_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_usd","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_khr","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"usd_100","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"usd_50","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"usd_20","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"usd_10","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_20000","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_10000","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_5000","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_2000","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_1000","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_500","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"khr_100","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
