const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_hr_employees_working_info",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"employee_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"department_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"group_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"position_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"policy_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"roster","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"employee_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"employee_type_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"resigned_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_method","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"self_tax","type":"bigint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salary_tax","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"absent_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"permission_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"monthly_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_early_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"normal_ot_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday_ot_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weekend_ot_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"kpi_type","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"additions","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"deductions","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"annual_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"monthly_annual_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"special_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sick_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"other_leave","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"seniority","type":"double","auto":false,"nullable":false,"hasDefault":true},
    {"name":"no_seniority","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attendance_bonus","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"special_bonus","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tra_acc_allowance","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"union","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pension","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salary_two_time","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"employee_level","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
