const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_loan_borrowers",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"application_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unique_type_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unique_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"first_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"last_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gender","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"email","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"dob","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"marital_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"working_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"country_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"province_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"district_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"commune_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"village_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"street_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"home_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"longitude","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"latitude","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"photo","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
