const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_pos_settings",
  primaryKey: ["pos_id"],
  hidden: ["pin_code","password_reason"],
  columns: [
    {"name":"pos_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"cat_limit","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"pro_limit","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"default_category","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"show_category","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"show_qty","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"show_item","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"default_customer","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"default_biller","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"default_warehouse","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"display_time","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"cf_title1","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cf_title2","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cf_value1","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cf_value2","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receipt_printer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"allow_total_cash_in_hand","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"cash_drawer_codes","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"focus_add_item","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"add_manual_product","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_selection","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"add_customer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"toggle_category_slider","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"toggle_subcategory_slider","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cancel_sale","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"suspend_sale","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"print_items_list","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"finalize_sale","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"today_sale","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"open_hold_bills","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"close_register","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"keyboard","type":"tinyint","auto":false,"nullable":false,"hasDefault":false},
    {"name":"pos_printers","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"java_applet","type":"tinyint","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_button_color","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"tooltips","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"paypal_pro","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"stripe","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rounding","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"char_per_line","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pin_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"envato_username","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"version","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"after_sale_page","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_order","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"authorize","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"toggle_brands_slider","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"remote_printing","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"printer","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_printers","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"auto_print","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_details","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"local_printers","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pos_type","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"interest_rate","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"separate","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"sale_due","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"password_reason","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"show_floor","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"show_categories","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"wait_number","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"dynamic_date","type":"date","auto":false,"nullable":false,"hasDefault":false},
    {"name":"member_card","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"time_duration","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"print_product","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"coupon_card","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"show_close_register_products","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"pos_multi_payment","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
  ],
});
