const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_reward_exchange_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"reward_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"reward_exchange_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"exchange_product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"exchange_product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"exchange_product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"exchange_quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"exchange_unit_quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"exchange_product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"exchange_product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_product_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_product_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_product_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_quantity","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_unit_quantity","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"set_quantity","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"purchase_unit_cost","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"max_serial","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"comment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cost","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warranty","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"free","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"piece","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"wpiece","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"width","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"height","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"square","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"raw_materials","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"commission","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"foc","type":"float","auto":false,"nullable":false,"hasDefault":false},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
