const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_prescription",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"staff_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"sale_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_status","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_items","type":"smallint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_sale_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"api","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shop","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"diagnosis_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hash","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"image","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"history","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"symptoms","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"medicine","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"laboratory","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"vital_signs","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"age","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weight","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"height","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
