const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_installments",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"price","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"installment_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_period","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_method","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principal_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"char","auto":false,"nullable":false,"hasDefault":true},
    {"name":"term","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"frequency_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"frequency","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"penalty_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
  ],
});
