const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_suspended_bills",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"refer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"start_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"count","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"suspend_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"table_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"table_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"print_status","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"bill_status","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"cgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"igst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"original_price","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"free","type":"int","auto":false,"nullable":false,"hasDefault":true},
  ],
});
