const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_con_trucks",
  primaryKey: [],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"plate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"driver_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"diesel_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"driver_assistant","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"driver_fuel_fee","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"assistant_fuel_fee","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"in_range_km","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"in_range_litre","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"out_range_km","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"out_range_litre","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"m3","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"litre","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_from","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_to","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_litre","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_from2","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_to2","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"moving_litre2","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_from","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_to","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_litre","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_from2","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_to2","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"waiting_litre2","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"big_truck","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
  ],
});
