const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_pay_salary_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"approved_att_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salary_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"employee_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"working_day","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"absent","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"permission","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"normal_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weekend_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday_ot","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"basic_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"absent_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"permission_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"late_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deduction","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"overtime","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"additions","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition_amount","type":"double","auto":false,"nullable":false,"hasDefault":true},
    {"name":"deductions","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deduction_amount","type":"double","auto":false,"nullable":false,"hasDefault":true},
    {"name":"seniority","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"seniority_response_tax","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"severance","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"indemnity","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"severance_riel","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"indemnity_riel","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nssf_salary_usd","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nssf_salary_riel","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"contributory_nssf","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pension_by_staff","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pension_by_company","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"health_nssf","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"accident_nssf","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gross_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gross_salary_riel","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"spouse","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"children","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"spouse_children_reduction","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"Taxbasesalary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pre_salary","type":"double","auto":false,"nullable":false,"hasDefault":true},
    {"name":"cash_advanced","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_declaration","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_percent","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_payment","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_payment_riel","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_salary","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_pay","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_paid","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salary_paid","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"normal_ot_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weekend_ot_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"holiday_ot_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_commission","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
