const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_saving_products",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_period","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"initial_amount_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"initial_amount_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_rate_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"balance_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"balance_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"withdraw_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"withdraw_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"withdraw_fee_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"withdraw_fee_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_fee_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"deposit_fee_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"transfer_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"transfer_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"transfer_fee_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"transfer_fee_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"entry_fee_min","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"entry_fee_max","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
