const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_credit_note",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"customer","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"default_total_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"total_items","type":"smallint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"paid","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"sale_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"staff_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"surcharge","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_sale_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_sale_total","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"rounding","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hash","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"credit_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_method","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"currency_rate_kh","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"voided_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"voided_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"zone_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currencies","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"print_time","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"subject","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
