const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_con_sales",
  primaryKey: [],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"customer","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"grand_total","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"actual_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"from_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"location_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"location_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"truck_charge","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pump_charge","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_items","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
