const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_approved",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"sale_order_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_request_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_order_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"transfer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quote_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"approved_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"checked_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"checked_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"checked_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"rejected_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rejected_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rejected_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"delivery_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"unapproved_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unapproved_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unapproved_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"preparation_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"preparation_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"preparation_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"issued_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"issued_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"issued_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"acknowledged_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"acknowledged_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"acknowledged_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"received_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"received_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"received_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"stock_received_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"stock_received_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"stock_received_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quality_checked_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quality_checked_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quality_checked_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"procurement_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"procurement_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"procurement_date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
