const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_shop_settings",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"shop_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"shop_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"description","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"about_link","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"terms_link","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"privacy_link","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"contact_link","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"payment_text","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"follow_text","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"facebook","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"twitter","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"google_plus","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"instagram","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"email","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cookie_message","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cookie_link","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"slider","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"shipping","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"envato_username","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"version","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"logo","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_details","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"products_page","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide0","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"products_description","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"private","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide_price","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"stripe","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"scanpay","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
  ],
});
