const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_hr_employees",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"finger_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nric_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"empcode","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"candidate","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"candidate_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"firstname","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"lastname","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"firstname_kh","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"lastname_kh","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"photo","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"dob","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"retirement","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gender","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"email","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nationality","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"marital_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"non_resident","type":"bigint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nssf","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"nssf_number","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"book_type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"work_permit_number","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"workbook_number","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pob","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"module_type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"operator","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"commission_rate","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
