const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_debit_note_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"debit_note_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quantity","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"quantity_received","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quantity_balance","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"weight","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_cost","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_unit_cost","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"base_unit_cost","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"status","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"status_change","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"change_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"supplier_part_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
