const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_purchases",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"purchase_order_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_plan_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"order_ref","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"request_ref","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"supplier_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"supplier","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"note","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"total","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount_id","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"order_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"shipping","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"due_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"surcharge","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"return_purchase_ref","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_purchase_total","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"cgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"igst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"is_asset","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_account","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"bank_code","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"useful_life","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"residual_value","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expenses_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"confirm_date","type":"datetime","auto":false,"nullable":false,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"suspend_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"adjust_paid","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"total_qty","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"receive_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
  ],
});
