const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_return_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"return_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_unit_price","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"comment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gst","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sgst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"igst","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
  ],
});
