const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sh_teachers",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"lastname","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"firstname","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"lastname_other","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"firstname_other","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"photo","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"dob","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gender","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"email","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pob","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"bank_account","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"address","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"nationality","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"non_resident","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
