const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_stock_received_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"stock_received_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"purchase_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reward_exchange_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"parent_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"unit_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_cost","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"net_unit_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quantity","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"unit_quantity","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"weight","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_tax","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_discount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"double","auto":false,"nullable":false,"hasDefault":false},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"comment","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_cbm","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sup_qty","type":"double","auto":false,"nullable":true,"hasDefault":true},
  ],
});
