const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sh_student_yearly",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"exam_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"academic_year","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"student_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"program_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"program_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grade_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grade_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"class_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"class_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"month_score","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"month_rank","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"month_average","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"section_rank","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"section_average","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rank","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"average","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"result","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"credit","type":"char","auto":false,"nullable":true,"hasDefault":true},
  ],
});
