const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sale_items",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"sale_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"check_in","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"check_out","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_code","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_name","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"purchase_unit_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"real_unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"original_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"net_unit_price","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"unit_price","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"unit_quantity","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"product_unit_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_unit_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"to_warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_tax","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax_rate_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tax","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"discount","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_discount","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"subtotal","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"serial_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"max_serial","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"comment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"gst","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"option_comment_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"addition_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warranty","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"hide","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"free","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"weight","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"total_weight","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"piece","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"wpiece","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"width","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"height","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"square","type":"float","auto":false,"nullable":true,"hasDefault":true},
    {"name":"raw_materials","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"combo_product","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"extract_product","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"extract_cost","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"commission","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expiry","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"start_time","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"end_time","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"period_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"category_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"making_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"foc","type":"float","auto":false,"nullable":false,"hasDefault":false},
    {"name":"from_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"destination_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"timeout_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"timeout_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"date_booking_ticket","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"room_option","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_row_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"consignment_item_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"item_barcode","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
