const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_stock_counts",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"type","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"initial_file","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"final_file","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"brands","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"brand_names","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"categories","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"category_names","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"products","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"rows","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"differences","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"matches","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"missing","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"finalized","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
  ],
});
