const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sh_tickets",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"academic_year","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"student_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"family_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"family_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"relationship","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grade_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"class_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"behavior","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"old_ticket","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"solver","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"assign_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"assign_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"response_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
  ],
});
