const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_users",
  primaryKey: ["id"],
  hidden: ["password","pin_code","salt","activation_code","forgotten_password_code","forgotten_password_time","remember_code","password_reset_code"],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"group_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"emp_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"emp_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"first_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"last_name","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"username","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"password","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"gender","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"company","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"phone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"email","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"multi_biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"warehouse_id","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"company_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"show_cost","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"show_price","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"view_right","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"edit_right","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"allow_discount","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"language","type":"char","auto":false,"nullable":false,"hasDefault":true},
    {"name":"active","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"last_login","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"last_ip_address","type":"varbinary","auto":false,"nullable":true,"hasDefault":true},
    {"name":"ip_address","type":"varbinary","auto":false,"nullable":true,"hasDefault":true},
    {"name":"pin_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salt","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"activation_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"forgotten_password_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"forgotten_password_time","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"remember_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_on","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"avatar","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"nationality","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"position","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"employeed_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"user_type","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"award_points","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"expired_date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"zone_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"multi_zone","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"save_point","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"is_remote_allow","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"basic_salary","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"commission","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"commission_product","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"saleman_group_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_group","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_commission","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"salesman_area","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"share_commissions","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payroll_option","type":"tinyint","auto":false,"nullable":false,"hasDefault":true},
    {"name":"signature","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"technician","type":"int","auto":false,"nullable":false,"hasDefault":true},
    {"name":"password_reset_code","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"product_commission_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"fuel_time_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"money_change","type":"text","auto":false,"nullable":true,"hasDefault":false},
  ],
});
