const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_loan_applications",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"borrower_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"borrower","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"principal_amount","type":"double","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"interest_rate","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_period","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"interest_method","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"insurance_rate","type":"decimal","auto":false,"nullable":false,"hasDefault":true},
    {"name":"grace_interest_charge","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"term","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"frequency","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"loan_product_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"borrower_type_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"loan_officer_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"teller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
