const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_rewards_exchange",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"timestamp","auto":false,"nullable":false,"hasDefault":true},
    {"name":"reference_no","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"category","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"type","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"biller","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"warehouse_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"project_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"company_id","type":"int","auto":false,"nullable":false,"hasDefault":false},
    {"name":"company","type":"varchar","auto":false,"nullable":false,"hasDefault":false},
    {"name":"grand_total","type":"decimal","auto":false,"nullable":false,"hasDefault":false},
    {"name":"paid","type":"decimal","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"payment_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"payment_term","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"updated_at","type":"timestamp","auto":false,"nullable":true,"hasDefault":true},
    {"name":"note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"staff_note","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"currency","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"currencies","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"return_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"saleman_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"delivery_status","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"zone_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"image","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"module_type","type":"varchar","auto":false,"nullable":false,"hasDefault":true},
    {"name":"print_time","type":"int","auto":false,"nullable":false,"hasDefault":true},
  ],
});
