const BaseModel = require('../core/BaseModel');

module.exports = new BaseModel({
  table: "aura_sh_study_infos",
  primaryKey: ["id"],
  hidden: [],
  columns: [
    {"name":"id","type":"int","auto":true,"nullable":false,"hasDefault":false},
    {"name":"date","type":"date","auto":false,"nullable":true,"hasDefault":true},
    {"name":"biller_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"student_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"academic_year","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"program_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"program","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"skill_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grade_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"grade","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"section_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"class_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"class","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"batch","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"timeshift_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"course_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"room_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"tuition_sale_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"issue_invoice","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"child_no","type":"tinyint","auto":false,"nullable":true,"hasDefault":true},
    {"name":"attachment","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
    {"name":"description","type":"text","auto":false,"nullable":true,"hasDefault":false},
    {"name":"type","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"status","type":"char","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_by","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"created_at","type":"datetime","auto":false,"nullable":true,"hasDefault":true},
    {"name":"scholarship_id","type":"int","auto":false,"nullable":true,"hasDefault":true},
    {"name":"generation","type":"varchar","auto":false,"nullable":true,"hasDefault":true},
  ],
});
