/**
 * Reads a phpMyAdmin / mysqldump .sql file and generates, for EVERY table:
 *   models/<table>.model.js
 *   controllers/<table>.controller.js
 *   routes/<table>.route.js
 * plus routes/index.js (mounts all routes) and schema.json.
 *
 * Usage:  node scripts/generate.js path/to/aura_v1_db.sql
 */
const fs = require('fs');
const path = require('path');

const sqlPath = process.argv[2];
if (!sqlPath || !fs.existsSync(sqlPath)) {
  console.error('Usage: node scripts/generate.js path/to/file.sql');
  process.exit(1);
}

const ROOT = path.join(__dirname, '..');
const PREFIX = 'aura_';

// Columns that must never be exposed or written through the generic API
const HIDDEN_ANY = /password|passwd|^salt$|reset_code|activation_code|remember_code|pin_code|^pin$|token|secret|api_key|private_key/i;
const HIDDEN_BY_TABLE = { aura_api_keys: ['key'] };

const sql = fs.readFileSync(sqlPath, 'utf8');
const tableRe = /CREATE TABLE (?:IF NOT EXISTS )?`([^`]+)` \(\r?\n([\s\S]*?)\r?\n\)\s*ENGINE/g;

const tables = [];
let m;
while ((m = tableRe.exec(sql))) {
  const name = m[1];
  const columns = [];
  let primaryKey = [];

  for (const raw of m[2].split(/\r?\n/)) {
    const line = raw.trim();
    if (line.startsWith('`')) {
      const c = /^`([^`]+)`\s+([a-zA-Z]+)/.exec(line);
      if (!c) continue;
      columns.push({
        name: c[1],
        type: c[2].toLowerCase(),
        auto: /AUTO_INCREMENT/i.test(line),
        nullable: !/NOT NULL/i.test(line),
        hasDefault: /DEFAULT/i.test(line),
      });
    } else if (/^PRIMARY KEY/i.test(line)) {
      const p = /\(([^)]+)\)/.exec(line);
      if (p) primaryKey = p[1].split(',').map((s) => s.replace(/`|\(\d+\)/g, '').trim());
    }
  }

  const hidden = columns
    .map((c) => c.name)
    .filter((n) => HIDDEN_ANY.test(n) || (HIDDEN_BY_TABLE[name] || []).includes(n));

  tables.push({ name, primaryKey, columns, hidden });
}

// wipe old generated files
for (const dir of ['models', 'controllers', 'routes']) {
  fs.mkdirSync(path.join(ROOT, dir), { recursive: true });
  for (const f of fs.readdirSync(path.join(ROOT, dir))) fs.unlinkSync(path.join(ROOT, dir, f));
}

const toPath = (t) => t.replace(new RegExp('^' + PREFIX), '').replace(/_/g, '-');
const seen = new Map();
const mounts = [];

for (const t of tables) {
  const p = toPath(t.name);
  if (seen.has(p)) throw new Error(`Route collision: ${t.name} and ${seen.get(p)} -> /${p}`);
  seen.set(p, t.name);

  const cols = t.columns.map((c) => JSON.stringify(c)).join(',\n    ');
  fs.writeFileSync(
    path.join(ROOT, 'models', `${t.name}.model.js`),
    `const BaseModel = require('../core/BaseModel');\n\n` +
      `module.exports = new BaseModel({\n  table: ${JSON.stringify(t.name)},\n  primaryKey: ${JSON.stringify(t.primaryKey)},\n` +
      `  hidden: ${JSON.stringify(t.hidden)},\n  columns: [\n    ${cols},\n  ],\n});\n`
  );
  fs.writeFileSync(
    path.join(ROOT, 'controllers', `${t.name}.controller.js`),
    `const createController = require('../core/createController');\nconst model = require('../models/${t.name}.model');\n\n` +
      `// Add custom handlers here, e.g. module.exports = { ...createController(model), myHandler };\n` +
      `module.exports = createController(model);\n`
  );
  fs.writeFileSync(
    path.join(ROOT, 'routes', `${t.name}.route.js`),
    `const createRouter = require('../core/createRouter');\nconst model = require('../models/${t.name}.model');\n` +
      `const controller = require('../controllers/${t.name}.controller');\n\nmodule.exports = createRouter(controller, model);\n`
  );
  mounts.push({ table: t.name, path: p, hasKey: t.primaryKey.length > 0 });
}

fs.writeFileSync(
  path.join(ROOT, 'routes', 'index.js'),
  `// AUTO-GENERATED by scripts/generate.js - do not edit by hand\nconst express = require('express');\nconst router = express.Router();\n\n` +
    `const resources = [\n` +
    mounts.map((r) => `  { path: ${JSON.stringify(r.path)}, table: ${JSON.stringify(r.table)}, hasKey: ${r.hasKey}, router: require('./${r.table}.route') },`).join('\n') +
    `\n];\n\nfor (const r of resources) router.use('/' + r.path, r.router);\n\n` +
    `router.resources = resources.map(({ path, table, hasKey }) => ({ path: '/api/' + path, table, hasKey }));\n\nmodule.exports = router;\n`
);

fs.writeFileSync(path.join(ROOT, 'schema.json'), JSON.stringify(tables, null, 2));

console.log(`Generated ${tables.length} tables -> models, controllers, routes`);
console.log(`Tables without primary key (list+create only): ${tables.filter((t) => !t.primaryKey.length).map((t) => t.name).join(', ') || 'none'}`);
console.log(`Composite keys: ${tables.filter((t) => t.primaryKey.length > 1).map((t) => t.name + '(' + t.primaryKey.join(',') + ')').join(', ') || 'none'}`);
console.log(`Hidden columns: ${tables.filter((t) => t.hidden.length).map((t) => t.name + '[' + t.hidden.join(',') + ']').join(', ') || 'none'}`);
